### ISSUE TITLE
Open-Source LuaX Transpiler

### ISSUE THREAD

**Issue by tooolbox** [bvisness/bvisness.me#1]
Hey there, read your article at https://bvisness.me/luax/

I am hoping you would consider open-sourcing LuaX (or rather, vend it in its own module) for use in the Go webserver [Algernon](https://github.com/xyproto/algernon/) which uses Lua as its engine.  Algernon already has many options for templating systems but I have been pining for exactly LuaX, for exactly the reasons you talk about in your blog post.

Down the road it would be awesome to combine LuaX and [Teal](https://github.com/teal-language/tl) (which Algernon supports) so you have the equivalent of JSX + TypeScript, but that could be a later step.

**Comment by bvisness** [comment]
Since LuaX is my personal project, I'm not interested in placing in a separate package or in any way maintaining it for others to use. However, the contents of the `bhp` folder are now available under the MIT license and you are therefore free to use the LuaX source code under the terms laid out in [LICENSE](https://github.com/bvisness/bvisness.me/blob/main/bhp/LICENSE). In addition, if you publish a fork of LuaX, I would appreciate if you credit my version of LuaX as an inspiration.

Thanks for your interest!
